### PR TITLE
Create journal-week-2.md

### PR DESCRIPTION
**Pull request by MStaehling**

### CODE REVIEW

**Comment by gatorpazz** [comment]
Good start, keep it up! :+1:

**Comment by gatorpazz** [comment]
Change your name to Steve, good journal, much technical knowledge, very good, :+1:

**Comment by JessyRiordan** [comment]
Good job, there is a lot of information in there! :+1:

**Comment by sjoyal** [comment]
Speaking of networking, I sent you an invitation to connect on LinkedIn. Looks like some of your information added multiple times on there. Good journal! :+1:

**Comment by BFGriffith** [comment]
A lot of information and very thoroughly organized notes. :+1:

**Pull request merged**
